# Generated by Django 5.0.7 on 2024-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercity',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='weathercity',
            name='city',
            field=models.CharField(max_length=30, unique=True, verbose_name='Введите название города'),
        ),
    ]
