# Generated by Django 5.0.7 on 2024-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathercity_options_alter_weathercity_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercity',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Введите название города'),
        ),
    ]
